import { Button, GroupBox, ScrollView, StyleMetrics, ListView } from "std-widgets.slint";
import { Account } from "account-item.slint";
import { AccountInner } from "account-inner.slint";
import { HorizontalSpacing, SectionTitle } from "../../components/components.slint";

export component AccountsList inherits GroupBox {
    in-out property <[AccountInner]> accounts;
    in-out property <int> current-index;

    callback selected(int);

    title: @tr("Other Accounts");

    ListView {
        preferred-height: accounts.length * (48px + StyleMetrics.layout-spacing);
        max-height: 3 * 48px + 2 * StyleMetrics.layout-spacing;
        for account[index] in accounts:
            HorizontalLayout {
                padding-bottom: StyleMetrics.layout-spacing;
                Account {
                    account: account;
                }

                HorizontalSpacing {}

                Button {
                    text: @tr("Select");
                    clicked => {
                        root.current-index = index;
                        selected(index);
                    }
                    enabled: index != current-index;
                }
            }
    }
}