import { HorizontalBox, Palette, StyleMetrics, VerticalBox, Button, GroupBox, LineEdit } from "std-widgets.slint";
import { Title, HorizontalSpacing, SecondaryText, SubTitle, SettingsGroup, MyText, VerticalSpacing } from "../../components/components.slint";
import { Account } from "account-item.slint";
import { AccountInner } from "account-inner.slint";
import { AccountsList } from "accounts-list.slint";

export { AccountInner }

export component AccountsPage inherits VerticalBox {
    in-out property <int> current-index;
    in-out property <[AccountInner]> accounts;

    callback open-login-dialog();
    callback del-acc(int);
    callback edit-acc(int, AccountInner);
    callback switch-acc(int);

    property <bool> edit: false;
    property <bool> switch: false;

    Title { text: @tr("Account"); }

    Rectangle {
        background: Palette.control-background;
        border-radius: 8px;
        vertical-stretch: 0;

        VerticalBox {
            HorizontalLayout {
                Account {
                    account: accounts[current-index];
                }

                HorizontalSpacing {}

                // Buttons
                VerticalLayout {
                    spacing: StyleMetrics.layout-spacing;

                    edit-btn := Button {
                        text: @tr("Edit");
                        clicked => {
                            edit = !edit;
                            switch = false;
                        }
                    }

                    switch-btn := Button {
                        text: @tr("Switch");
                        clicked => {
                            edit = false;
                            switch = !switch;
                        }
                    }
                }
            }

            if (edit): VerticalLayout {
                spacing: StyleMetrics.layout-spacing;
                
                SettingsGroup {
                    title: @tr("Edit {}", accounts[current-index].user-name);
                    Row {
                        MyText {
                            text: @tr("Name");
                        }
                        LineEdit {
                            text: accounts[current-index].user-name;
                            edited(text) => {
                                accounts[current-index].user-name = text;
                                edit-acc(current-index, accounts[current-index])
                            }
                        }
                    }
                    Row {
                        MyText {
                            text: @tr("UUID");
                        }
                        LineEdit {
                            text: accounts[current-index].uuid;
                            edited(text) => {
                                accounts[current-index].uuid = text;
                                edit-acc(current-index, accounts[current-index])
                            }
                        }
                    }
                    Row {
                        MyText {
                            text: @tr("Token");
                        }
                        LineEdit {
                            text: accounts[current-index].token;
                            edited(text) => {
                                accounts[current-index].token = text;
                                edit-acc(current-index, accounts[current-index])
                            }
                        }
                    }
                }

                HorizontalLayout {
                    HorizontalSpacing {}
                    Button {
                        text: @tr("Delete");
                        clicked => del-acc(current-index);
                    }
                }
            }

            if (switch): VerticalLayout {
                spacing: StyleMetrics.layout-spacing;

                AccountsList {
                    accounts: accounts;
                    current-index <=> root.current-index;
                    selected(index) => switch-acc(index);
                }

                HorizontalLayout {
                    HorizontalSpacing {}
                    Button {
                        text: @tr("Add");
                        clicked => open-login-dialog();
                    }
                }
            }
        }
    }

    VerticalSpacing {}
}