import { StandardButton } from "std-widgets.slint";
export { LoginDialog } from "login-dialog.slint";
export { AddGameDialog } from "add-game-dialog.slint";
export { EditGameDialog } from "edit-game-dialog.slint";

export enum MsgID {
    AccNotSelected,     // On launch, not select account
    BothNotSelected,    // On launch, not select account and game
    CopyUserCodeFailed, // On login, copy usercode failed, with user code provided
    DelAccConfirm,      // Confirm to delete an account
    DelGameConfirm,     // Confirm to delete a game
    DLFailed,           // Download failed, with reason
    GameNotSelected,    // On launch, not select game
    LoadAccFailed,      // On init, failed to load account list, with reason
    LoadConfigFailed,   // On init, failed to load config, with reason
    LoadGameFailed,     // On init, failed to load game list, with reason
    LoginFailed,        // On launch, failed to login, with reason
    LaunchFailed,       // On launch, failed to launch game, with reason
    OAuthFailed,        // On add account, OAuth Error, with reason
    VersionExists,      // On add game, version already exists
    WeakPtrError,       // Failed to upgrade a weak pointer
}

export component AskDialog inherits Dialog {
    in property <MsgID> msgid;
    in property <string> extra-str: "";

    VerticalLayout {
        text := Text {}
    }

    states [
        DelAccConfirm when msgid == MsgID.DelAccConfirm: {
            text.text: @tr("Are you sure to delete this account?");
        }
        DelGameConfirm when msgid == MsgID.DelGameConfirm: {
            text.text: @tr("All the files under this Minecraft installation's folder will be deleted. Continue?");
        }
    ]

    StandardButton { kind: yes; }
    StandardButton { kind: no; }
}

export component MsgDialog inherits Dialog {
    in property <MsgID> msgid;
    in property <string> extra-str: "";

    VerticalLayout {
        text := Text {}
    }

    states [
        AccNotSelected when msgid == MsgID.AccNotSelected: {
            text.text: @tr("Please select an account.");
        }
        BothNotSelected when msgid == MsgID.BothNotSelected: {
            text.text: @tr("Please select an account and the Minecraft version.");
        }
        CopyUserCodeFailed when msgid == MsgID.CopyUserCodeFailed: {
            text.text: @tr("Failed to copy your user code, please enter {0} manually.", extra-str);
        }
        DLFailed when msgid == MsgID.DLFailed: {
            text.text: @tr("Download failed: {0}", extra-str);
        }
        GameNotSelected when msgid == MsgID.GameNotSelected: {
            text.text: @tr("Please select the Minecraft version.");
        }
        LoadAccFailed when msgid == MsgID.LoadAccFailed: {
            text.text: @tr("Failed to load account list: {0}", extra-str);
        }
        LoadConfigFailed when msgid == MsgID.LoadConfigFailed: {
            text.text: @tr("Failed to load config: {0}", extra-str);
        }
        LoadGameFailed when msgid == MsgID.LoadGameFailed: {
            text.text: @tr("Failed to load Minecraft installation list: {0}", extra-str);
        }
        LoginFailed when msgid == MsgID.LoginFailed: {
            text.text: @tr("Failed to login.");
        }
        LaunchFailed when msgid == MsgID.LaunchFailed: {
            text.text: @tr("Failed to start.");
        }
        OAuthFailed when msgid == MsgID.OAuthFailed: {
            text.text: @tr("Failed to load OAuth login.");
        }
    ]

    StandardButton { kind: ok; }
}
