import { Palette } from "std-widgets.slint";
export component Title inherits Text {
    font-size: 24px;
    font-weight: 700;
    padding-bottom: 4px;
}

export component SubTitle inherits Text {
    font-size: 16px;    
}

export component SectionTitle inherits Text {
    font-size: 12px;
    font-weight: 700;    
}

export component SecondaryText inherits Text {
    color: Palette.control-foreground.darker(0.2);
}