version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "daily"
      time: "21:00"
      timezone: "Asia/Shanghai"
    groups:
      cargo:
        patterns:
          - "*"
