[workspace]
members = [
    "crates/app",
    "crates/downloader",
    "crates/frontend",
    "crates/java",
    "crates/mc",
    "crates/utils",
]
resolver = "2"

[workspace.package]
version = "0.3.0"
edition = "2024"
authors = ["constant-e <fmn_tzx@outlook.com>"]
license = "Apache 2.0"

[workspace.dependencies]
log = "0.4.33"
reqwest = { version = "0.13.4", features = ["form", "json", "stream"] }
serde_json = "1.0.151"
slint = "1.17.1"
tokio = { version = "1.53.1", features = ["full"] }
