[package]
name = "cemcl"
version = "0.1.0"
authors = ["constant-e <fmn_tzx@outlook.com>"]
edition = "2021"
license = "Apache 2.0"

[dependencies]
log = "0.4.22"
serde_json = "1.0.122"
slint = "1.7.1"

[build-dependencies]
slint-build = "1.7.1"
