[package]
name = "cemcl"
version = "0.2.0"
authors = ["constant-e <fmn_tzx@outlook.com>"]
edition = "2021"
license = "Apache 2.0"

[dependencies]
env_logger = "0.11.5"
futures = "0.3.30"
log = "0.4.22"
reqwest = "0.12.7"
serde_json = "1.0.128"
slint = "1.7.2"
tokio = { version = "1.40.0", features = ["full"] }
uuid = { version = "1.10.0", features = ["v4", "fast-rng", "macro-diagnostics"] }
zip = "2.2.0"

[build-dependencies]
slint-build = "1.7.2"
