import { Title, SettingsGroup, SubTitle, VerticalSpacing, MyText, MySpinBox } from "../../components/components.slint";
import { ComboBox, StandardButton, StandardTableView, Switch, LineEdit, VerticalBox, HorizontalBox, GridBox } from "std-widgets.slint";

import { MCConfig } from "game.slint";

export component AddGameDialog inherits Dialog {
    title: @tr("Add a Game");
    preferred-height: 600px;
    preferred-width: 800px;

    in-out property <int> game-index <=> game-table.current-row;
    in-out property <[[StandardListViewItem]]> game-list <=> game-table.rows;
    in-out property <int> game-type <=> game-combo-box.current-index;

    in-out property <int> mod-index <=> mod-table.current-row;
    in-out property <[[StandardListViewItem]]> mod-list <=> mod-table.rows;
    in-out property <int> mod-type <=> mod-combo-box.current-index;

    in-out property <MCConfig> game-config;

    callback get-default-game-config();
    callback get-game-list(int);
    // mc combo index, mc index, mod combo index
    callback get-mod-list(int, int, int);
    // mc combo, mc, mod combo, mod
    callback add-game(int, int, int, int, MCConfig);

    VerticalBox {
        padding: 0px;

        Title { text: @tr("Add a Game"); }
        HorizontalBox {
            padding: 0px;

            VerticalBox {
                padding: 0px;

                SubTitle { text: @tr("Minecraft Version"); }
                game-combo-box := ComboBox {
                    model: [@tr("All"), @tr("Release"), @tr("Snapshot"), @tr("Old Alpha"), @tr("Old Beta")];
                    selected => { root.get-game-list(self.current-index); }
                }
                game-table := StandardTableView {
                    columns: [
                        { title: @tr("Version") },
                        { title: @tr("Type") }
                    ];
                    min-width: 200px;

                    current-row-changed(row) => {
                        if mod-combo-box.current-index != 0 {
                            root.get-mod-list(game-combo-box.current-index, row, mod-combo-box.current-index);
                        }
                    }
                }
            }
    
            VerticalBox {
                padding: 0px;

                SubTitle { text: @tr("Mod Loader"); }
                mod-combo-box := ComboBox {
                    model: [@tr("None"), "Forge", "Fabric"];
                    selected => {
                        if self.current-index != 0 {
                            root.get-mod-list(game-combo-box.current-index, game-table.current-row, self.current-index);
                        } else {
                            root.mod-list = [];
                        }
                        
                    }
                }
                mod-table := StandardTableView {
                    min-width: 200px;
                    columns: [
                        { title: @tr("Version") },
                        { title: @tr("Modified") }
                    ];
                }
            }

            VerticalLayout {
                SettingsGroup {
                    title: @tr("Customize");
                    vertical-stretch: 0;

                    Row {
                        MyText { text: @tr("Window height"); }
                        MySpinBox {
                            value <=> game-config.height;
                        }
                    }

                    Row {
                        MyText { text: @tr("Window width"); }
                        MySpinBox {
                            value <=> game-config.width;
                        }
                    }

                    Row {
                        MyText { text: @tr("Description"); }
                        LineEdit {
                            text <=> game-config.description;
                        }
                    }

                    Row {
                        MyText { text: @tr("Game args"); }
                        LineEdit {
                            text <=> game-config.game-args;
                        }
                    }

                    Row {
                        MyText { text: @tr("Java path"); }
                        LineEdit {
                            text <=> game-config.java-path;
                        }
                    }

                    Row {
                        MyText { text: @tr("JVM args"); }
                        LineEdit {
                            text <=> game-config.jvm-args;
                        }
                    }

                    Row {
                        MyText { text: @tr("Wrapper"); }
                        LineEdit {
                            text <=> game-config.wrapper;
                        }
                    }

                    Row {
                        MyText { text: @tr("Minimum memory"); }
                        LineEdit {
                            text <=> game-config.xms;
                        }
                    }

                    Row {
                        MyText { text: @tr("Maximum memory"); }
                        LineEdit {
                            text <=> game-config.xmx;
                        }
                    }

                    Row {
                        Switch {
                            text: @tr("Separated");
                            checked <=> game-config.separated;
                        }
                    }
                }

                VerticalSpacing {}
            }
        }
    }

    StandardButton { kind: cancel; }
    StandardButton {
        kind: ok;
        clicked => {
            root.add-game(game-combo-box.current-index, game-table.current-row, mod-combo-box.current-index, mod-table.current-row, game-config);
        }
    }
}
