import { StandardButton, Button, Switch, LineEdit, GridBox, ComboBox, HorizontalBox } from "std-widgets.slint";
import { SubTitle, SettingsGroup, MyText, MySpinBox, JavaVersionSelector } from "../../components/components.slint";

import { MCConfig } from "game.slint";

export component EditGameDialog inherits Dialog {
    title: @tr("Edit a Game");
    preferred-height: 200px;
    preferred-width: 400px;

    in-out property <MCConfig> game-config;
    in-out property <string> version;

    // Java selector (separate from config)
    in-out property <[string]> java-combo-model;
    in-out property <int> java-index;

    callback del-game();
    callback edit-game(MCConfig);

    VerticalLayout {
        SettingsGroup {
            title: @tr("Edit {}", version);

            Row {
                MyText { text: @tr("Window height"); }
                MySpinBox {
                    value <=> game-config.height;
                }
            }

            Row {
                MyText { text: @tr("Window width"); }
                MySpinBox {
                    value <=> game-config.width;
                }
            }

            Row {
                MyText { text: @tr("Description"); }
                LineEdit {
                    text <=> game-config.description;
                }
            }

            Row {
                MyText { text: @tr("Game args"); }
                LineEdit {
                    text <=> game-config.game-args;
                }
            }

            Row {
                MyText { text: @tr("Java path"); }
                JavaVersionSelector {
                    model <=> root.java-combo-model;
                    current-index <=> root.java-index;
                }
            }

            Row {
                MyText { text: @tr("JVM args"); }
                LineEdit {
                    text <=> game-config.jvm-args;
                }
            }

            Row {
                MyText { text: @tr("Wrapper"); }
                LineEdit {
                    text <=> game-config.wrapper;
                }
            }

            Row {
                MyText { text: @tr("Minimum memory"); }
                LineEdit {
                    text <=> game-config.xms;
                }
            }

            Row {
                MyText { text: @tr("Maximum memory"); }
                LineEdit {
                    text <=> game-config.xmx;
                }
            }

            Row {
                Switch {
                    colspan: 2;
                    text: @tr("Separated");
                    horizontal-stretch: 1;
                    checked <=> game-config.separated;
                }    
            }
        }
    }

    Button {
        text: @tr("Delete");
        dialog-button-role: action;
        clicked => { root.del-game() }
    }
    StandardButton { kind: cancel; }
    StandardButton {
        kind: ok;
        clicked => { root.edit-game(game-config) }
    }
}
