import { StandardButton, TabWidget, LineEdit, GridBox } from "std-widgets.slint";

export component AddAccDialog inherits Dialog {
    title: @tr("Add a Account");
    preferred-height: 200px;
    preferred-width: 400px;

    in-out property <int> account-type-index <=> tab-widget.current-index;
    in-out property <string> online-acc <=> online-acc-input.text;
    in-out property <string> online-pwd <=> online-pwd-input.text;
    in-out property <string> offline-name <=> offline-name-input.text;
    in-out property <string> offline-uuid <=> offline-uuid-input.text;
    in-out property <string> other-acc-type <=> other-acc-type-input.text;
    in-out property <string> other-name <=> other-name-input.text;
    in-out property <string> other-token <=> other-token-input.text;
    in-out property <string> other-uuid <=> other-uuid-input.text;

    tab-widget := TabWidget {
        Tab {
            title: @tr("Online Account");

            GridBox {
                Text {
                    text: @tr("Account: ");
                    col: 0;
                    row: 0;
                }
                online-acc-input := LineEdit {
                    col: 1;
                    row: 0;
                }
            
                Text {
                    text: @tr("Password: ");
                    col: 0;
                    row: 1;
                }
                online-pwd-input := LineEdit {
                    col: 1;
                    row: 1;
                }

                Rectangle {
                    preferred-height: 100%;
                    row: 2;
                }
            }
        }

        Tab {
            title: @tr("Offline Account");

            GridBox {
                Text {
                    text: @tr("Name: ");
                    col: 0;
                    row: 0;
                }
                offline-name-input := LineEdit {
                    col: 1;
                    row: 0;
                }
            
                Text {
                    text: @tr("UUID: ");
                    col: 0;
                    row: 1;
                }
                offline-uuid-input := LineEdit {
                    col: 1;
                    row: 1;
                }

                Rectangle {
                    preferred-height: 100%;
                    row: 2;
                }
            }
        }

        Tab {
            title: @tr("Other Account");

            GridBox {
                Text {
                    text: @tr("Account Type: ");
                    col: 0;
                    row: 0;
                }
                other-acc-type-input := LineEdit {
                    col: 1;
                    row: 0;
                }
            
                Text {
                    text: @tr("Token: ");
                    col: 0;
                    row: 1;
                }
                other-token-input := LineEdit {
                    col: 1;
                    row: 1;
                }

                Text {
                    text: @tr("User Name: ");
                    col: 0;
                    row: 2;
                }
                other-name-input := LineEdit {
                    col: 1;
                    row: 2;
                }

                Text {
                    text: @tr("UUID: ");
                    col: 0;
                    row: 3;
                }
                other-uuid-input := LineEdit {
                    col: 1;
                    row: 3;
                }

                Rectangle {
                    preferred-height: 100%;
                    row: 4;
                }
            }
        }
    }

    StandardButton { kind: cancel; }
    StandardButton { kind: ok; }
}
