import { Title, SubTitle } from "components/components.slint";
import { ComboBox, StandardButton, StandardTableView, Switch } from "std-widgets.slint";

export component AddGameDialog inherits Dialog {
    title: @tr("Add a Game");
    preferred-height: 600px;
    preferred-width: 800px;

    in-out property <int> game-index <=> game-table.current-row;
    in-out property <[[StandardListViewItem]]> game-list <=> game-table.rows;
    in-out property <int> game-type <=> game-combo-box.current-index;

    in-out property <int> mod-index <=> mod-table.current-row;
    in-out property <[[StandardListViewItem]]> mod-list <=> mod-table.rows;
    in-out property <int> mod-type <=> mod-combo-box.current-index;

    in-out property <string> args <=> args-input.text;
    in-out property <string> config-height <=> height-input.text;
    in-out property <string> config-width <=> width-input.text;
    in-out property <string> description <=> description-input.text;
    in-out property <string> java-path <=> java-path-input.text;
    in-out property <bool> separated <=> separated-switch.checked;
    in-out property <string> xms <=> xms-input.text;
    in-out property <string> xmx <=> xmx-input.text;

    callback game-combo-box-changed(string);

    VerticalLayout {
        Title { text: @tr("Add a Game"); }
        HorizontalLayout {
            spacing: 4px;
    
            VerticalLayout {
                SubTitle { text: @tr("Minecraft Version"); }
                game-combo-box := ComboBox {
                    model: ["All", "Release", "Snapshot"];
                    selected(mod) => { root.game-combo-box-changed(mod); }
                }
                game-table := StandardTableView {
                    preferred-height: 100%;
                    columns: [
                        { title: @tr("Version") },
                        { title: @tr("Type") }
                    ];
                }
            }
    
            VerticalLayout {
                SubTitle { text: @tr("Mod Loader"); }
                mod-combo-box := ComboBox { model: ["None", "Forge", "Fabric"]; }
                mod-table := StandardTableView {
                    preferred-height: 100%;
                    columns: [
                        { title: @tr("Version") },
                        { title: @tr("Type") }
                    ];
                }
            }
    
            VerticalLayout {
                SubTitle { text: @tr("Customize"); }
                GridLayout {
                    Text {
                        text: @tr("Description: ");
                        col: 0;
                        row: 0;
                    }
                    description-input := TextInput {
                        col: 1;
                        row: 0;
                    }
                
                    Text {
                        text: @tr("Java Path: ");
                        col: 0;
                        row: 1;
                    }
                    java-path-input := TextInput {
                        col: 1;
                        row: 1;
                    }
    
                    Text {
                        text: @tr("Window Height: ");
                        col: 0;
                        row: 2;
                    }
                    height-input := TextInput {
                        col: 1;
                        row: 2;
                    }
    
                    Text {
                        text: @tr("Window Width: ");
                        col: 0;
                        row: 3;
                    }
                    width-input := TextInput {
                        col: 1;
                        row: 3;
                    }
    
                    Text {
                        text: @tr("Minimum Memory: ");
                        col: 0;
                        row: 4;
                    }
                    xms-input := TextInput {
                        col: 1;
                        row: 4;
                    }
            
                    Text {
                        text: @tr("Maximum Memory: ");
                        col: 0;
                        row: 5;
                    }
                    xmx-input := TextInput {
                        col: 1;
                        row: 5;
                    }
            
                    Text {
                        text: @tr("Launch Arguments: ");
                        col: 0;
                        row: 6;
                    }
                    args-input := TextInput {
                        col: 1;
                        row: 6;
                    }
                    
                    separated-switch := Switch {
                        text: @tr("Enable Separated Version");
                        row: 7;
                    }
            
                    Rectangle {
                        preferred-height: 100%;
                        row: 8;
                    }
                }
            }
        }
    }

    StandardButton { kind: cancel; }
    StandardButton { kind: ok; }
}