import { Title, SubTitle } from "components/components.slint";
import { ComboBox, StandardButton, StandardTableView, Switch, LineEdit, VerticalBox, HorizontalBox, GridBox } from "std-widgets.slint";

export component AddGameDialog inherits Dialog {
    title: @tr("Add a Game");
    preferred-height: 600px;
    preferred-width: 800px;

    in-out property <int> game-index <=> game-table.current-row;
    in-out property <[[StandardListViewItem]]> game-list <=> game-table.rows;
    in-out property <int> game-type <=> game-combo-box.current-index;

    in-out property <int> mod-index <=> mod-table.current-row;
    in-out property <[[StandardListViewItem]]> mod-list <=> mod-table.rows;
    in-out property <int> mod-type <=> mod-combo-box.current-index;

    in-out property <string> config-height <=> height-input.text;
    in-out property <string> config-width <=> width-input.text;
    in-out property <string> description <=> description-input.text;
    in-out property <string> game-args <=> game-args-input.text;
    in-out property <string> java-path <=> java-path-input.text;
    in-out property <string> jvm-args <=> jvm-args-input.text;
    in-out property <bool> separated <=> separated-switch.checked;
    in-out property <string> xms <=> xms-input.text;
    in-out property <string> xmx <=> xmx-input.text;

    callback game-combo-box-changed(int);
    callback game-list-changed(int);
    callback mod-combo-box-changed(int);

    VerticalBox {
        padding: 0px;

        Title { text: @tr("Add a Game"); }
        HorizontalBox {
            padding: 0px;

            VerticalBox {
                padding: 0px;

                SubTitle { text: @tr("Minecraft Version"); }
                game-combo-box := ComboBox {
                    model: [@tr("All"), @tr("Release"), @tr("Snapshot")];
                    selected => { root.game-combo-box-changed(self.current-index); }
                }
                game-table := StandardTableView {
                    preferred-height: 100%;
                    columns: [
                        { title: @tr("Version") },
                        { title: @tr("Type") }
                    ];
                    current-row-changed(row) => { root.game-list-changed(row); }
                }
            }
    
            VerticalBox {
                padding: 0px;

                SubTitle { text: @tr("Mod Loader"); }
                mod-combo-box := ComboBox {
                    model: [@tr("None"), "Forge", "Fabric"];
                    selected => { root.mod-combo-box-changed(self.current-index); }
                }
                mod-table := StandardTableView {
                    preferred-height: 100%;
                    columns: [
                        { title: @tr("Version") },
                        { title: @tr("Modified") }
                    ];
                }
            }
    
            VerticalBox {
                padding: 0px;

                SubTitle { text: @tr("Customize"); }
                GridBox {
                    padding: 0px;

                    Text {
                        text: @tr("Description: ");
                        vertical-alignment: center;
                        col: 0;
                        row: 0;
                    }
                    description-input := LineEdit {
                        col: 1;
                        row: 0;
                    }
                
                    Text {
                        text: @tr("Java Path: ");
                        vertical-alignment: center;
                        col: 0;
                        row: 1;
                    }
                    java-path-input := LineEdit {
                        col: 1;
                        row: 1;
                    }
    
                    Text {
                        text: @tr("Window Height: ");
                        vertical-alignment: center;
                        col: 0;
                        row: 2;
                    }
                    height-input := LineEdit {
                        col: 1;
                        row: 2;
                    }
    
                    Text {
                        text: @tr("Window Width: ");
                        vertical-alignment: center;
                        col: 0;
                        row: 3;
                    }
                    width-input := LineEdit {
                        col: 1;
                        row: 3;
                    }
    
                    Text {
                        text: @tr("Minimum Memory: ");
                        vertical-alignment: center;
                        col: 0;
                        row: 4;
                    }
                    xms-input := LineEdit {
                        col: 1;
                        row: 4;
                    }
            
                    Text {
                        text: @tr("Maximum Memory: ");
                        vertical-alignment: center;
                        col: 0;
                        row: 5;
                    }
                    xmx-input := LineEdit {
                        col: 1;
                        row: 5;
                    }
            
                    Text {
                        text: @tr("Java Arguments: ");
                        vertical-alignment: center;
                        col: 0;
                        row: 6;
                    }
                    jvm-args-input := LineEdit {
                        col: 1;
                        row: 6;
                    }

                    Text {
                        text: @tr("Minecraft Arguments: ");
                        vertical-alignment: center;
                        col: 0;
                        row: 7;
                    }
                    game-args-input := LineEdit {
                        col: 1;
                        row: 7;
                    }
                    
                    separated-switch := Switch {
                        text: @tr("Enable Separated Version");
                        row: 8;
                    }
            
                    Rectangle {
                        preferred-height: 100%;
                        row: 9;
                    }
                }
            }
        }
    }

    StandardButton { kind: cancel; }
    StandardButton { kind: ok; }
}
