import { Button, StandardTableView, VerticalBox, HorizontalBox } from "std-widgets.slint";
import { Title, SubTitle } from "components/components.slint";
export { Messages } from "messages.slint";

export { AddAccDialog } from "add-acc-dialog.slint";
export { AddGameDialog } from "add-game-dialog.slint";
export { AskDialog, ErrorDialog, WarnDialog } from "dialogs.slint";
export { EditAccDialog } from "edit-acc-dialog.slint";
export { EditGameDialog } from "edit-game-dialog.slint";
export { Settings } from "settings.slint";

export component AppWindow inherits Window {
    preferred-height: 600px;
    preferred-width: 800px;
    title: "CE Minecraft Launcher";
    icon: @image-url("../pic/icon.png");

    in-out property <int> acc-index <=> acc-table.current-row;
    in-out property <int> game-index <=> game-table.current-row;
    in-out property <[[StandardListViewItem]]> acc-list <=> acc-table.rows;
    in-out property <[[StandardListViewItem]]> game-list <=> game-table.rows;
    in-out property <string> popup-msg;

    callback click-add-acc-btn();
    callback click-add-game-btn();
    callback click-edit-acc-btn();
    callback click-edit-game-btn();
    callback click-settings-btn();
    callback click-start-btn();
    
    public function close-popup() { popup.close(); }
    public function show-popup() { popup.show(); }
    public function popup-set-downloading() { popup-msg = @tr("Downloading"); }
    public function popup-set-launching() { popup-msg = @tr("Launching"); }
    public function popup-set-logging-in() { popup-msg = @tr("Logging in"); }

    popup := PopupWindow {
        close-on-click: false;
        height: root.height;
        width: root.width;
        Rectangle {
            background: root.background.darker(0.1);
            height: 300px;
            width: 400px;
            x: (root.width - self.width) / 2;
            y: (root.height - self.height) / 2;
            Title { text: root.popup-msg; }
        }
    }

    VerticalBox {
        padding: 8px;

        Title { text: "CE Minecraft Launcher"; }

        HorizontalBox {
            padding: 0px;

            VerticalBox {
                horizontal-stretch: 1/4;
                padding: 0px;

                SubTitle { text: @tr("Account"); }

                acc-table := StandardTableView {
                    columns: [
                        { title: @tr("Name") },
                        { title: @tr("Type") }
                    ];
                }

                HorizontalBox {
                    padding: 0px;

                    Rectangle { preferred-width: 100%; }

                    Button {
                        text: @tr("Add");
                        clicked => { root.click-add-acc-btn() } 
                    }
        
                    Button {
                        text: @tr("Edit");
                        clicked => { root.click-edit-acc-btn() }
                    }
                }
            }

            VerticalBox {
                horizontal-stretch: 3/4;
                padding: 0px;

                SubTitle { text: @tr("Minecraft Version"); }

                game-table := StandardTableView {
                    columns: [
                        { title: @tr("Version") },
                        { title: @tr("Type") },
                        { title: @tr("Description") }
                    ];
                }

                HorizontalBox {
                    padding: 0px;

                    Rectangle { preferred-width: 100%; }

                    Button {
                        text: @tr("Add");
                        clicked => { root.click-add-game-btn() } 
                    }
        
                    Button {
                        text: @tr("Edit");
                        clicked => { root.click-edit-game-btn() }
                    }
                }
            }
        }

        HorizontalBox {
            padding: 0px;

            Button {
                text: @tr("Settings");
                clicked => { root.click-settings-btn() }
            }

            Rectangle { preferred-width: 100%; }

            Button {
                text: @tr("Start");
                clicked => { root.click-start-btn(); }
            }
        }
    }
}
