import { Button, StandardTableView } from "std-widgets.slint";
import { Title, SubTitle } from "components/components.slint";

export { AddAccDialog } from "add-acc-dialog.slint";
export { AddGameDialog } from "add-game-dialog.slint";
export { AskDialog, ErrorDialog, WarnDialog } from "dialogs.slint";
export { EditAccDialog } from "edit-acc-dialog.slint";
export { EditGameDialog } from "edit-game-dialog.slint";
export { Settings } from "settings.slint";

export component AppWindow inherits Window {
    preferred-height: 600px;
    preferred-width: 800px;
    title: "CE Minecraft Launcher";
    icon: @image-url("../pic/icon.png");

    in-out property <int> acc-index <=> acc-table.current-row;
    in-out property <int> game-index <=> game-table.current-row;
    in-out property <[[StandardListViewItem]]> acc-list <=> acc-table.rows;
    in-out property <[[StandardListViewItem]]> game-list <=> game-table.rows;

    callback click-add-acc-btn();
    callback click-add-game-btn();
    callback click-edit-acc-btn();
    callback click-edit-game-btn();
    callback click-settings-btn();
    callback click-start-btn();
    
    public function close-popup() { popup.close(); }
    public function show-popup() { popup.show(); }

    popup := PopupWindow {
        close-on-click: false;
        height: root.height;
        width: root.width;
        Rectangle {
            background: root.background.darker(0.1);
            height: 300px;
            width: 400px;
            x: (root.width - self.width) / 2;
            y: (root.height - self.height) / 2;
            Title { text: @tr("Launching"); }
        }
    }

    VerticalLayout {
        padding: 8px;

        Title { text: "CE Minecraft Launcher"; }

        HorizontalLayout {
            spacing: 4px;

            VerticalLayout{
                horizontal-stretch: 0.25;

                SubTitle { text: @tr("Account"); }

                acc-table := StandardTableView {
                    columns: [
                        { title: @tr("Name") },
                        { title: @tr("Type") }
                    ];
                }

                HorizontalLayout {
                    Rectangle { preferred-width: 100%; }

                    Button {
                        text: @tr("Add");
                        clicked => { root.click-add-acc-btn() } 
                    }
        
                    Button {
                        text: @tr("Edit");
                        clicked => { root.click-edit-acc-btn() }
                    }
                }
            }

            VerticalLayout {
                horizontal-stretch: 0.75;

                SubTitle { text: @tr("Minecraft Version"); }

                game-table := StandardTableView {
                    columns: [
                        { title: @tr("Version") },
                        { title: @tr("Type") },
                        { title: @tr("Description") }
                    ];
                }

                HorizontalLayout {
                    Rectangle { preferred-width: 100%; }

                    Button {
                        text: @tr("Add");
                        clicked => { root.click-add-game-btn() } 
                    }
        
                    Button {
                        text: @tr("Edit");
                        clicked => { root.click-edit-game-btn() }
                    }
                }
            }
        }

        HorizontalLayout {
            Button {
                text: @tr("Settings");
                clicked => { root.click-settings-btn() }
            }

            Rectangle { preferred-width: 100%; }

            Button {
                text: @tr("Start");
                clicked => { root.click-start-btn(); }
            }
        }
    }
}