import { Button, StandardTableView } from "std-widgets.slint";
import { ErrorDialog } from "dialogs.slint";
import { Settings } from "settings.slint";
import { Title, SubTitle } from "components/components.slint";
import { AddAccDialog } from "add-acc-dialog.slint";

export { AddAccDialog, ErrorDialog, Settings }

export component AppWindow inherits Window {
    preferred-height: 600px;
    preferred-width: 800px;
    title: "CE Minecraft Launcher";

    in-out property <int> acc-index <=> acc-table.current-row;
    in-out property <int> game-index <=> game-table.current-row;
    in-out property <[[StandardListViewItem]]> acc-list <=> acc-table.rows;
    in-out property <[[StandardListViewItem]]> game-list <=> game-table.rows;

    callback click-add-acc-btn();
    callback click-add-game-btn();
    callback click-edit-acc-btn();
    callback click-edit-game-btn();
    callback click-settings-btn();
    callback click-start-btn();

    VerticalLayout {
        padding: 4px;

        Title { text: "CE Minecraft Launcher"; }

        HorizontalLayout {
            spacing: 4px;

            VerticalLayout{
                horizontal-stretch: 0.25;

                SubTitle { text: @tr("Account"); }

                acc-table := StandardTableView {
                    columns: [
                        { title: @tr("Name") },
                        { title: @tr("Type") }
                    ];
                }

                HorizontalLayout {
                    Rectangle { preferred-width: 100%; }

                    Button {
                        text: @tr("Add");
                        clicked => { root.click-add-acc-btn() } 
                    }
        
                    Button {
                        text: @tr("Edit");
                        clicked => { root.click-edit-acc-btn() }
                    }
                }
            }

            VerticalLayout {
                horizontal-stretch: 0.75;

                SubTitle { text: @tr("Minecraft Version"); }

                game-table := StandardTableView {
                    columns: [
                        { title: @tr("Version") },
                        { title: @tr("Type") },
                        { title: @tr("Description") }
                    ];
                }

                HorizontalLayout {
                    Rectangle { preferred-width: 100%; }

                    Button {
                        text: @tr("Add");
                        clicked => { root.click-add-game-btn() } 
                    }
        
                    Button {
                        text: @tr("Edit");
                        clicked => { root.click-edit-game-btn() }
                    }
                }
            }
        }

        HorizontalLayout {
            Button {
                text: @tr("Settings");
                clicked => { root.click-settings-btn() }
            }

            Rectangle { preferred-width: 100%; }

            Button {
                text: @tr("Start");
                clicked => { root.click-start-btn() }
            }
        }
    }
}