import { Button, ListView } from "std-widgets.slint";

struct Account {
    account-type: string,
    user-name: string
}

struct Game {
    description: string,
    game-type: string,
    version: string
}

export component CEMCL inherits Window {
    callback clicked-add-btn();
    callback clicked-edit-btn();
    callback clicked-settings-btn();
    callback clicked-start-btn();

    out property <int> acc-list-index <=> acc-list-view.row;
    out property <int> ver-list-index <=> ver-list-view.row;

    in-out property <[Account]> acc-list : [{account-type: "test", user-name: "test"}, {account-type: "test2", user-name: "test2"}];
    in-out property <[Game]> ver-list;

    preferred-width: 800px;
    preferred-height: 600px;
    padding: 8px;
    title: @tr("CE Minecraft Launcher");
    VerticalLayout {
        Text {
            preferred-width: 100%;
            text: @tr("CE Minecraft Launcher");
            font-size: 32px;
            font-weight: 800;
        }

        GridLayout {
            Row {
                Text {
                    text: @tr("Account");
                }

                Text {
                    text: @tr("Minecraft Version");
                }
            }
            
            Row {
                acc-list-view := ListView {
                    for acc[i] in acc-list: Rectangle {
                        Text { text: acc.user-name; }
                        Text { text: acc.account-type; }
                    }
                }

                ver-list-view := ListView {
                    for ver[i] in ver-list: Rectangle {
                        Text { text: ver.version; }
                        Text { text: ver.game-type; }
                        Text {
                            text: ver.description;
                            preferred-width: 100%;
                        }
                    }
                }
            }
        }

        HorizontalLayout {
            preferred-height: 50px;
            preferred-width: 100%;

            settings-btn := Button {
                text: @tr("Settings");
                preferred-width: 100px;
                clicked => {
                    clicked-settings-btn();
                }
            }
            
            Rectangle {
                preferred-width: 100%;
            }

            add-btn := Button {
                text: @tr("New");
                preferred-width: 100px;
                clicked => {
                    clicked-add-btn();
                }
            }

            edit-btn := Button {
                text: @tr("Edit");
                preferred-width: 100px;
                clicked => {
                    clicked-edit-btn();
                }
            }

            start-btn := Button {
                text: @tr("Start");
                preferred-width: 100px;
                clicked => {
                    clicked-start-btn();
                }
            }
        }
    }
}