import { Button, ListView, StandardTableView } from "std-widgets.slint";

export component CEMCL inherits Window {
    callback clicked-add-btn();
    callback clicked-edit-btn();
    callback clicked-settings-btn();
    callback clicked-start-btn();

    out property <[[StandardListViewItem]]> acc-table-rows <=> acc-table-view.rows;
    out property <[[StandardListViewItem]]> ver-table-rows <=> ver-table-view.rows;

    preferred-width: 800px;
    preferred-height: 600px;
    padding: 8px;
    title: @tr("CE Minecraft Launcher");
    VerticalLayout {
        Text {
            preferred-width: 100%;
            text: @tr("CE Minecraft Launcher");
            font-size: 32px;
            font-weight: 800;
        }

        GridLayout {
            Row {
                Text {
                    text: @tr("Account");
                }

                Text {
                    text: @tr("Minecraft Version");
                }
            }
            
            Row {
                acc-table-view := StandardTableView {

                }

                ver-table-view := StandardTableView {

                }
            }
        }

        HorizontalLayout {
            preferred-height: 50px;
            preferred-width: 100%;

            settings-btn := Button {
                text: @tr("Settings");
                preferred-width: 100px;
                clicked => {
                    clicked-settings-btn();
                }
            }
            
            Rectangle {
                preferred-width: 100%;
            }

            add-btn := Button {
                text: @tr("New");
                preferred-width: 100px;
                clicked => {
                    clicked-add-btn();
                }
            }

            edit-btn := Button {
                text: @tr("Edit");
                preferred-width: 100px;
                clicked => {
                    clicked-edit-btn();
                }
            }

            start-btn := Button {
                text: @tr("Start");
                preferred-width: 100px;
                clicked => {
                    clicked-start-btn();
                }
            }
        }
    }
}