import { StandardButton, Button, LineEdit, GridBox } from "std-widgets.slint";
import { SubTitle } from "components/components.slint";

export component EditAccDialog inherits Dialog {
    title: @tr("Edit an Account");
    preferred-height: 200px;
    preferred-width: 400px;

    in-out property <string> acc-type <=> acc-type-input.text;
    in-out property <string> name <=> name-input.text;
    in-out property <string> token <=> token-input.text;
    in-out property <string> uuid <=> uuid-input.text;

    callback del-clicked();

    GridBox {
        padding: 0px;

        SubTitle {
            text: @tr("Account ") + name;
            col: 0;
            row: 0;
        }

        Text {
            text: @tr("Account Type");
            vertical-alignment: center;
            col: 0;
            row: 1;
        }
        acc-type-input := LineEdit {
            col: 1;
            row: 1;
        }
    
        Text {
            text: @tr("Token");
            vertical-alignment: center;
            col: 0;
            row: 2;
        }
        token-input := LineEdit {
            col: 1;
            row: 2;
        }

        Text {
            text: @tr("User Name");
            vertical-alignment: center;
            col: 0;
            row: 3;
        }
        name-input := LineEdit {
            col: 1;
            row: 3;
        }

        Text {
            text: @tr("UUID");
            vertical-alignment: center;
            col: 0;
            row: 4;
        }
        uuid-input := LineEdit {
            col: 1;
            row: 4;
        }

        Rectangle {
            preferred-height: 100%;
            row: 5;
        }
    }

    Button {
        text: @tr("Delete");
        dialog-button-role: action;
        clicked => { root.del-clicked() }
    }
    StandardButton { kind: cancel; }
    StandardButton { kind: ok; }
}
