export global Messages {
    in-out property <string> acc-not-selected: @tr("Please select an account first.");
    in-out property <string> acc-or-game-not-selected: @tr("Please select an account and a game first.");
    in-out property <string> del-game-confirm: @tr("All the files under this game's dir will be deleted. Continue?");
    in-out property <string> game-not-selected: @tr("Please select a game first.");
    in-out property <string> load-acc-failed: @tr("Failed to load account list. Reason: ");
    in-out property <string> load-config-failed: @tr("Failed to load config. Reason: ");
    in-out property <string> load-game-failed: @tr("Failed to load game list. Reason: ");
    in-out property <string> warn: @tr("Warning");
}
