import { TabWidget, ScrollView, StandardButton, Switch, SpinBox, LineEdit, GroupBox, VerticalBox, GridBox, HorizontalBox } from "std-widgets.slint";
import { Title, SectionTitle } from "components/components.slint";

export component Settings inherits Dialog {
    preferred-height: 600px;
    preferred-width: 800px;
    title: @tr("Settings");

    // About
    in-out property <string> authors;
    in-out property <string> version;

    // Launcher Settings
    // General
    in-out property <bool> close-after-launch <=> close-after-launch-box.checked;
    in-out property <string> game-path <=> game-path-input.text;
    // Downloading Settings
    in-out property <int> concurrency <=> concurrency-input.value;
    in-out property <string> assets-source <=> assets-source-input.text;
    in-out property <string> libraries-source <=> libraries-source-input.text;
    in-out property <string> game-source <=> game-source-input.text;
    in-out property <string> fabric-source <=> fabric-source-input.text;
    in-out property <string> forge-source <=> forge-source-input.text;

    // Default Minecraft Settings
    in-out property <string> java-path <=> java-path-input.text;
    in-out property <string> config-height <=> height-input.text;
    in-out property <string> config-width <=> width-input.text;
    in-out property <string> xms <=> xms-input.text;
    in-out property <string> xmx <=> xmx-input.text;

    VerticalBox {
        padding: 0px;

        Title { text: @tr("Settings"); }
        
        TabWidget {
            Tab {
                title: @tr("Launcher Settings");

                ScrollView {
                    VerticalBox {
                        GroupBox {
                            title: @tr("General");
    
                            GridBox {
                                padding: 0px;

                                Text {
                                    text: @tr("Minecraft Path: ");
                                    col: 0;
                                    row: 0;
                                }
                                game-path-input := LineEdit {
                                    col: 1;
                                    row: 0;
                                }
        
                                close-after-launch-box := Switch {
                                    text: @tr("Close after Launching Game");
                                    col: 0;
                                    row: 1;
                                }
                            }
                        }
    
                        GroupBox {
                            title: @tr("Downloading Settings");
    
                            GridBox {
                                padding: 0px;

                                Text {
                                    text: @tr("Concurrency: ");
                                    col: 0;
                                    row: 0;
                                }
                                concurrency-input := SpinBox {
                                    col: 1;
                                    row: 0;
                                }
        
                                Text {
                                    text: @tr("Assets Source: ");
                                    col: 0;
                                    row: 1;
                                }
                                assets-source-input := LineEdit {
                                    col: 1;
                                    row: 1;
                                }
        
                                Text {
                                    text: @tr("Libraries Source: ");
                                    col: 0;
                                    row: 2;
                                }
                                libraries-source-input := LineEdit {
                                    col: 1;
                                    row: 2;
                                }
        
                                Text {
                                    text: @tr("Minecraft Source: ");
                                    col: 0;
                                    row: 3;
                                }
                                game-source-input := LineEdit {
                                    col: 1;
                                    row: 3;
                                }
                                
                                Text {
                                    text: @tr("Fabric Source: ");
                                    col: 0;
                                    row: 4;
                                }
                                fabric-source-input := LineEdit {
                                    col: 1;
                                    row: 4;
                                }
                                
                                Text {
                                    text: @tr("Forge Source: ");
                                    col: 0;
                                    row: 5;
                                }
                                forge-source-input := LineEdit {
                                    col: 1;
                                    row: 5;
                                }
                            }
                        }

                        Rectangle { preferred-height: 100%; }
                    }
                }
            }

            Tab {
                title: @tr("Default Minecraft Settings");

                ScrollView {
                    GridBox {
                        Text {
                            text: @tr("Java Path: ");
                            col: 0;
                            row: 0;
                        }
                        java-path-input := LineEdit {
                            col: 1;
                            row: 0;
                        }

                        Text {
                            text: @tr("Window Height: ");
                            col: 0;
                            row: 1;
                        }
                        height-input := LineEdit {
                            col: 1;
                            row: 1;
                        }
                    
                        Text {
                            text: @tr("Window Width: ");
                            col: 0;
                            row: 2;
                        }
                        width-input := LineEdit {
                            col: 1;
                            row: 2;
                        }
                    
                        Text {
                            text: @tr("Minimum Memory: ");
                            col: 0;
                            row: 3;
                        }
                        xms-input := LineEdit {
                            col: 1;
                            row: 3;
                        }
                    
                        Text {
                            text: @tr("Maximum Memory: ");
                            col: 0;
                            row: 4;
                        }
                        xmx-input := LineEdit {
                            col: 1;
                            row: 4;
                        }
    
                        Rectangle {
                            preferred-height: 100%;
                            row: 5;
                        }
                    }
                }
            }

            Tab {
                title: @tr("About");

                VerticalBox {
                    HorizontalBox {
                        alignment: center;
                        padding: 0px;

                        Image {
                            height: 44px;
                            width: 44px;
                            source: @image-url("../pic/icon.png");
                        }

                        Text {
                            text: "CE Minecraft Launcher";
                            font-size: 28px;
                            font-weight: 700;
                            padding: 8px;
                            vertical-alignment: center;
                        }
                    }
                    
                    Text { text: @tr("Version: ") + root.version; }
                    Text { text: @tr("Github Repository: ") + "https://github.com/constant-e/CEMCL"; }
                    Text { text: @tr("Developers: ") + root.authors; }
                    Text { text: @tr("License: ") + "Apache License 2.0"; }
                    Text {
                        text: @tr("Credits:\n") +
                            "   1. env_logger (https://crates.io/crates/env_logger)\n" +
                            "   2. futures (https://crates.io/crates/futures)\n" +
                            "   3. log (https://crates.io/crates/log)\n" +
                            "   4. reqwest (https://crates.io/crates/reqwest)\n" +
                            "   5. serde_json (https://crates.io/crates/serde_json)\n" +
                            "   6. slint (https://crates.io/crates/slint)\n" +
                            "   7. tokio (https://crates.io/crates/tokio)\n" +
                            "   8. uuid (https://crates.io/crates/uuid)\n" +
                            "   9. zip (https://crates.io/crates/zip)";
                    }
                    Rectangle { preferred-height: 100%; }
                }
            }
        }
    }

    StandardButton { kind: cancel;}
    StandardButton { kind: apply; }
}
