import { StandardButton } from "std-widgets.slint";
export { AddGameDialog } from "game/add-game-dialog.slint";
export { MCConfig } from "game/game.slint";
export { ForgeDownloadDialog } from "game/forge-download-dialog.slint";
export { LoginDialog } from "login-dialog.slint";
export { EditGameDialog } from "game/edit-game-dialog.slint";
export { AddJavaDialog } from "add-java-dialog.slint";

export enum AskID {
    DelAccConfirm,      // Confirm to delete an account
    DelGameConfirm,     // Confirm to delete a game
}

export component AskDialog inherits Dialog {
    in property <AskID> msgid;
    in property <string> extra-str: "";
    callback yes-clicked();

    VerticalLayout {
        text := Text {}
    }

    states [
        DelAccConfirm when msgid == AskID.DelAccConfirm: {
            text.text: @tr("Are you sure to delete this account?");
        }
        DelGameConfirm when msgid == AskID.DelGameConfirm: {
            text.text: @tr("All the files under this Minecraft installation's folder will be deleted. Continue?");
        }
    ]

    StandardButton {
        kind: yes;
        clicked => {
            root.yes-clicked();
            root.close();
        }
    }
    StandardButton {
        kind: no;
        clicked => root.close();
    }
}
