import { Button, StandardButton, StyleMetrics , VerticalBox, TabWidget, HorizontalBox, LineEdit } from "std-widgets.slint";
import { RoundedBackground, SubTitle, VerticalSpacing, HorizontalSpacing, SettingsGroup, SecondaryText, SectionTitle, MyText } from "../components/components.slint";

export component LoginDialog inherits Dialog {
    title: @tr("Add a Account");

    in-out property <string> user-name;
    in-out property <string> uuid;

    callback msa-clicked();
    callback msa-ok-clicked();
    callback offline-ok-clicked(string, string);

    VerticalBox {
        SubTitle { text: @tr("Add a Account"); }

        RoundedBackground {
            VerticalBox {
                offline-group := SettingsGroup {
                    title: @tr("Offline Account");

                    Row {
                        MyText { text: @tr("Name"); }
                        LineEdit {
                            text <=> root.user-name;
                        }
                    }

                    Row {
                        MyText { text: @tr("UUID"); }
                        LineEdit {
                            text <=> root.uuid;
                        }
                    }
                }
                
                HorizontalLayout {
                    HorizontalSpacing {}
                    Button {
                        text: @tr("OK");
                        clicked => offline-ok-clicked(user-name, uuid);
                    }
                }
            }
        }
        
        RoundedBackground {
            HorizontalBox {
                VerticalLayout {
                    SectionTitle {
                        vertical-alignment: center;
                        text: @tr("Microsoft Account");
                    }

                    SecondaryText {
                        vertical-alignment: center;
                        text: @tr("Your user code will be automatically copied.") + "\n" + @tr("Press OK after you finish logging in.");
                    }
                }

                VerticalSpacing { height: StyleMetrics.layout-spacing; }

                Button {
                    text: @tr("Open in Web Browser");
                    clicked => {
                        msa-clicked();
                        msa-ok-btn.enabled = true;
                    }
                }

                msa-ok-btn := Button {
                    text: @tr("OK");
                    enabled: false;
                    clicked => msa-ok-clicked();
                }
            }
        }
    }
}
