import { TabWidget, ScrollView, StandardButton, Switch, SpinBox, LineEdit, GroupBox, VerticalBox, GridBox, HorizontalBox } from "std-widgets.slint";
import { Title, SectionTitle, VerticalSpacing, SettingsGroup, HorizontalSpacing, MyText, MySpinBox } from "../components/components.slint";

export struct ConfigGeneral {
    close_after_launch: bool,
    game_path: string,
}

export struct ConfigDL {
    assets_source: string,
    libraries_source: string,
    game_source: string,
    fabric_source: string,
    forge_source: string,
    concurrency: int
}

export struct ConfigMC {
    java_path: string,
    path: string,
    width: int,
    wrapper: string,
    height: int,
    xms: string,
    xmx: string
}

export struct Config {
    general: ConfigGeneral,
    dl: ConfigDL,
    mc: ConfigMC
}

export component SettingsPage inherits VerticalBox {
    // About
    in-out property <string> authors;
    in-out property <string> version;

    // Launcher Settings
    in-out property <Config> config;

    callback set-config(Config);

    Title { text: @tr("Settings"); }
    
    TabWidget {
        Tab {
            title: @tr("Launcher Settings");
            ScrollView { VerticalBox {
                SettingsGroup {
                    vertical-stretch: 0;
                    title: @tr("General");
                    Row {
                        MyText { text: @tr("Minecraft Path"); }
                        LineEdit {
                            text <=> config.general.game-path;
                            edited => { set-config(root.config); }
                        }
                    }
                    Row {
                        Switch {
                            text: @tr("Quit after Launch");
                            checked <=> config.general.close-after-launch;
                            toggled => { set-config(root.config); }
                        }
                    }
                }

                SettingsGroup {
                    vertical-stretch: 0;
                    title: @tr("Downloading Settings");

                    Row {
                        MyText { text: @tr("Concurrency"); }
                        MySpinBox {
                            value <=> config.dl.concurrency;
                            edited => { set-config(root.config) }
                        }
                    }

                    Row {
                        MyText { text: @tr("Assets Source"); }
                        LineEdit {
                            text <=> config.dl.assets-source;
                            edited => { set-config(root.config); }
                        }
                    }

                    Row {
                        MyText { text: @tr("Libraries Source"); }
                        LineEdit {
                            text <=> config.dl.libraries-source;
                            edited => { set-config(root.config); }
                        }
                    }

                    Row {
                        MyText { text: @tr("Minecraft Source"); }
                        LineEdit {
                            text <=> config.dl.game-source;
                            edited => { set-config(root.config); }
                        }
                    }

                    Row {
                        MyText { text: @tr("Fabric Source"); }
                        LineEdit {
                            text <=> config.dl.fabric-source;
                            edited => { set-config(root.config); }
                        }
                    }

                    Row {
                        MyText { text: @tr("Forge Source"); }
                        LineEdit {
                            text <=> config.dl.forge-source;
                            edited => { set-config(root.config); }
                        }
                    }
                }

                VerticalSpacing {}
            } }
        }

        Tab {
            title: @tr("Default Minecraft Settings");
            ScrollView { VerticalBox {
                SettingsGroup {
                    vertical-stretch: 0;
                    title: @tr("Default Minecraft Settings");

                    Row {
                        MyText { text: @tr("Java Path"); }
                        LineEdit {
                            text <=> config.mc.java-path;
                            edited => { set-config(root.config); }
                        }
                    }

                    Row {
                        MyText { text: @tr("Wrapper"); }
                        LineEdit {
                            text <=> config.mc.wrapper;
                            edited => { set-config(root.config); }
                        }
                    }

                    Row {
                        MyText { text: @tr("Minimum Memory"); }
                        LineEdit {
                            text <=> config.mc.xms;
                            edited => { set-config(root.config); }
                        }
                    }

                    Row {
                        MyText { text: @tr("Maximum Memory"); }
                        LineEdit {
                            text <=> config.mc.xmx;
                            edited => { set-config(root.config); }
                        }
                    }

                    Row {
                        MyText { text: @tr("Window Height"); }
                        MySpinBox {
                            value <=> config.mc.height;
                            edited => { set-config(root.config); }
                        }
                    }

                    Row {
                        MyText { text: @tr("Window Width"); }
                        MySpinBox {
                            value <=> config.mc.width;
                            edited => { set-config(root.config); }
                        }
                    }
                }

                VerticalSpacing {}
            } }
        }

        Tab {
            title: @tr("About");
            VerticalBox {
                HorizontalBox {
                    alignment: center;
                    padding: 0px;
                    Image {
                        height: 44px;
                        width: 44px;
                        source: @image-url("../../pic/icon.png");
                    }
                    Text {
                        text: "CE Minecraft Launcher";
                        font-size: 28px;
                        font-weight: 700;
                        vertical-alignment: center;
                    }
                }
                
                Text { text: @tr("Version: ") + root.version; }
                Text { text: @tr("Github Repository: ") + "https://github.com/constant-e/CEMCL"; }
                Text { text: @tr("Developers: ") + root.authors; }
                Text { text: @tr("License: ") + "Apache License 2.0"; }
                Text {
                    text: @tr("Credits:\n") +
                        "   1. BMCLAPI2 (https://bmclapidoc.bangbang93.com/)\n" +
                        "   2. clipboard (https://crates.io/crates/clipboard)\n" +
                        "   3. env_logger (https://crates.io/crates/env_logger)\n" +
                        "   4. futures (https://crates.io/crates/futures)\n" +
                        "   5. log (https://crates.io/crates/log)\n" +
                        "   6. reqwest (https://crates.io/crates/reqwest)\n" +
                        "   7. serde_json (https://crates.io/crates/serde_json)\n" +
                        "   8. slint (https://crates.io/crates/slint)\n" +
                        "   9. tokio (https://crates.io/crates/tokio)\n" +
                        "   10. uuid (https://crates.io/crates/uuid)\n" +
                        "   11. webbrowser (https://crates.io/crates/webbrowser)\n" +
                        "   12. zip (https://crates.io/crates/zip)";
                }

                VerticalSpacing {}
            }
        }
    }
}
