import { VerticalBox, StandardTableView, HorizontalBox, Button } from "std-widgets.slint";
import { Title, HorizontalSpacing } from "../components/components.slint";

export component AccountsPage inherits VerticalBox {
    in-out property <int> current-index <=> table.current-row;
    in-out property <[[StandardListViewItem]]> model <=> table.rows;

    callback click-add-btn();
    callback click-edit-btn(index: int);

    Title { text: @tr("Account"); }

    table := StandardTableView {
        min-width: 250px;
        columns: [
            { title: @tr("Name") },
            { title: @tr("Type") }
        ];
    }

    HorizontalBox {
        padding: 0px;

        HorizontalSpacing {}

        add-btn := Button {
            text: @tr("Add");
            clicked => { click-add-btn() }
        }

        edit-btn := Button {
            text: @tr("Edit");
            clicked => { click-edit-btn(current-index) }
        }
    }
}