import { ProgressIndicator, VerticalBox, StandardTableView } from "std-widgets.slint";
import { Title, SectionTitle } from "../components/components.slint";

export component DownloaderPage inherits VerticalBox {
    in-out property <[[StandardListViewItem]]> in-progress-model <=> in-progress-table.rows;
    in-out property <[[StandardListViewItem]]> finished-model <=> finished_table.rows;

    Title { text: @tr("Downloader"); }

    SectionTitle { text: @tr("In progress"); }
    in-progress-table := StandardTableView {
        columns: [
            { title: @tr("Name") },
            { title: @tr("Progress") },
        ];
    }

    SectionTitle { text: @tr("Finished"); }
    finished_table := StandardTableView {
        columns: [
            { title: @tr("Name") },
            { title: @tr("State") },
        ];
    }
}