import { TabWidget, ScrollView, StandardButton, Switch, SpinBox, LineEdit, GroupBox, VerticalBox, GridBox, HorizontalBox } from "std-widgets.slint";
import { Title, SectionTitle, VerticalSpacing, SettingsGroup, SettingString, SettingBool, SettingInt, HorizontalSpacing } from "../components/components.slint";

export struct ConfigGeneral {
    close_after_launch: bool,
    game_path: string,
}

export struct ConfigDL {
    assets_source: string,
    libraries_source: string,
    game_source: string,
    fabric_source: string,
    forge_source: string,
    concurrency: int
}

export struct ConfigMC {
    java_path: string,
    width: string,
    height: string,
    xms: string,
    xmx: string
}

export struct Config {
    general: ConfigGeneral,
    dl: ConfigDL,
    mc: ConfigMC
}

export component SettingsPage inherits VerticalBox {
    // About
    in-out property <string> authors;
    in-out property <string> version;

    // Launcher Settings
    in-out property <Config> config;

    callback settings-changed();

    Title { text: @tr("Settings"); }
    
    TabWidget {
        Tab {
            title: @tr("Launcher Settings");
            ScrollView { VerticalBox {
                SettingsGroup {
                    vertical-stretch: 0;
                    title: @tr("General");
                    setting-bool-list: [
                        {
                            id: "close_after_launch",
                            name: @tr("Close after Launching Game"),
                            value: config.general.close-after-launch
                        }
                    ];
                    setting-string-list: [
                        {
                            id: "game_path",
                            name: @tr("Minecraft Path"),
                            value: config.general.game-path
                        }
                    ];
                    setting-bool-changed(id, value) => {
                        if (id == "close_after_launch") {
                            config.general.close-after-launch = value;
                        }
                        root.settings-changed();
                    };
                    setting-string-changed(id, value) => {
                        if (id == "game_path") {
                            config.general.game-path = value;
                        }
                        root.settings-changed();
                    };
                }

                SettingsGroup {
                    vertical-stretch: 0;
                    title: @tr("Downloading Settings");

                    setting-int-list: [
                        {
                            id: "concurrency",
                            name: @tr("Concurrency"),
                            value: config.dl.concurrency
                        }
                    ];

                    setting-string-list: [
                        {
                            id: "assets_source",
                            name: @tr("Assets Source"),
                            value: config.dl.assets-source
                        },
                        {
                            id: "libraries_source",
                            name: @tr("Libraries Source"),
                            value: config.dl.libraries-source
                        },
                        {
                            id: "game_source",
                            name: @tr("Minecraft Source"),
                            value: config.dl.game-source
                        },
                        {
                            id: "fabric_source",
                            name: @tr("Fabric Source"),
                            value: config.dl.fabric-source
                        },
                        {
                            id: "forge_source",
                            name: @tr("Forge Source"),
                            value: config.dl.forge-source
                        }
                    ];

                    setting-string-changed(id, value) => {
                        if (id == "assets_source") {
                            config.dl.assets-source = value;
                        } else if (id == "libraries_source") {
                            config.dl.libraries-source = value;
                        } else if (id == "game_source") {
                            config.dl.game-source = value;
                        } else if (id == "fabric_source") {
                            config.dl.fabric-source = value;
                        } else if (id == "forge_source") {
                            config.dl.forge-source = value;
                        }
                        root.settings-changed();
                    };

                    setting-int-changed(id, value) => {
                        if (id == "concurrency") {
                            config.dl.concurrency = value;
                        }
                        root.settings-changed();
                    }
                }

                VerticalSpacing {}
            } }
        }

        Tab {
            title: @tr("Default Minecraft Settings");
            ScrollView { VerticalBox {
                SettingsGroup {
                    vertical-stretch: 0;
                    title: @tr("Default Minecraft Settings");
                    setting-string-list: [
                        {
                            id: "java_path",
                            name: @tr("Java Path"),
                            value: config.mc.java-path
                        },
                        {
                            id: "height",
                            name: @tr("Window Height"),
                            value: config.mc.height
                        },
                        {
                            id: "width",
                            name: @tr("Window Width"),
                            value: config.mc.width
                        },
                        {
                            id: "xms",
                            name: @tr("Minimum Memory"),
                            value: config.mc.xms
                        },
                        {
                            id: "xmx",
                            name: @tr("Maximum Memory"),
                            value: config.mc.xmx
                        }
                    ];

                    setting-string-changed(id, value) => {
                        if (id == "java_path") {
                            config.mc.java-path = value;
                        } else if (id == "height") {
                            config.mc.height = value;
                        } else if (id == "width") {
                            config.mc.width = value;
                        } else if (id == "xms") {
                            config.mc.xms = value;
                        } else if (id == "xmx") {
                            config.mc.xmx = value;
                        }
                        root.settings-changed();
                    };
                }

                VerticalSpacing {}
            } }
        }

        Tab {
            title: @tr("About");
            VerticalBox {
                HorizontalBox {
                    alignment: center;
                    padding: 0px;
                    Image {
                        height: 44px;
                        width: 44px;
                        source: @image-url("../../pic/icon.png");
                    }
                    Text {
                        text: "CE Minecraft Launcher";
                        font-size: 28px;
                        font-weight: 700;
                        vertical-alignment: center;
                    }
                }
                
                Text { text: @tr("Version: ") + root.version; }
                Text { text: @tr("Github Repository: ") + "https://github.com/constant-e/CEMCL"; }
                Text { text: @tr("Developers: ") + root.authors; }
                Text { text: @tr("License: ") + "Apache License 2.0"; }
                Text {
                    text: @tr("Credits:\n") +
                        "   1. BMCLAPI2 (https://bmclapidoc.bangbang93.com/)\n" +
                        "   2. clipboard (https://crates.io/crates/clipboard)\n" +
                        "   3. env_logger (https://crates.io/crates/env_logger)\n" +
                        "   4. futures (https://crates.io/crates/futures)\n" +
                        "   5. log (https://crates.io/crates/log)\n" +
                        "   6. reqwest (https://crates.io/crates/reqwest)\n" +
                        "   7. serde_json (https://crates.io/crates/serde_json)\n" +
                        "   8. slint (https://crates.io/crates/slint)\n" +
                        "   9. tokio (https://crates.io/crates/tokio)\n" +
                        "   10. uuid (https://crates.io/crates/uuid)\n" +
                        "   11. webbrowser (https://crates.io/crates/webbrowser)\n" +
                        "   12. zip (https://crates.io/crates/zip)";
                }

                VerticalSpacing {}
            }
        }
    }
}
