name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest, macos-13, ubuntu-latest]
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup Rust
      run: rustup update
    - name: Install gettext and libxcb
      if: matrix.os == 'ubuntu-latest'
      run: sudo apt-get install gettext libxcb*
    - name: Build debug
      run: cargo build --verbose
    - name: Build release
      run: cargo build --release --verbose
    - name: Upload artifact
      uses: actions/upload-artifact@v4.3.6
      with:
        name: artifact-${{ matrix.os }}
        path: |
          target/*/cemcl
          target/*/cemcl.exe
