name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest, macos-13, ubuntu-latest]
    
    # For macOS
    env:
      DYLD_FRAMEWORK_PATH: /Users/runner/work/CEMCL/Qt/5.15.2/clang_64/lib
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        version: "5.15.2"
    - name: Install gettext
      if: matrix.os == 'macos-13'
      run: brew install gettext
    - name: Install gettext and xorg-dev
      if: matrix.os == 'ubuntu-latest'
      run: sudo apt install gettext xorg-dev
    - name: Install slint-tr-extractor
      if: matrix.os != 'windows-latest'
      run: cargo install slint-tr-extractor && export PATH=~/.cargo/bin:$PATH
    - name: Build debug
      run: cargo build --verbose
    - name: Build release
      run: cargo build --release --verbose
    # Windows is not support yet
    - name: Generate language file
      if: matrix.os != 'windows-latest'
      run: ./update_translations.sh --all
    # Windows only
    - name: Add dll files
      if: matrix.os == 'windows-latest'
      run: |
        windeployqt target/debug/cemcl.exe
        windeployqt target/release/cemcl.exe
    - name: Upload artifact
      uses: actions/upload-artifact@v4.3.6
      with:
        name: artifact-${{ matrix.os }}
        path: |
          target/*/iconengines
          target/*/imageformats
          target/*/platforms
          target/*/styles
          target/*/translations
          target/*/cemcl
          target/*/cemcl.exe
          target/*/*.dll
          target/*/locale
