name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest, macos-13, ubuntu-latest]
    
    # For macOS
    env:
      DYLD_FRAMEWORK_PATH: /Users/runner/work/CEMCL/Qt/5.15.2/clang_64/lib
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        version: "5.15.2"
    - name: Build debug
      run: cargo build --verbose
    - name: Build release
      run: cargo build --release --verbose
    # Windows is not support yet
    - name: Generate language file
      if: matrix.os != 'windows-latest'
      run: ./update_translations.sh --all
    - name: Upload artifact
      uses: actions/upload-artifact@v4.3.6
      with:
        name: artifact-${{ matrix.os }}
        path: |
          target/*/cemcl
          target/*/cemcl.exe
          target/*/locale

