name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest, macos-13, ubuntu-latest]
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        version: '6.8.1'
    - name: Install gettext and libxcb
      if: matrix.os == 'ubuntu-latest'
      run: sudo apt-get install gettext libxcb*
    - name: Install slint-tr-extractor
      if: matrix.os != 'windows-latest'
      run: cargo install slint-tr-extractor && export PATH=~/.cargo/bin:$PATH
    - name: Build debug
      run: cargo build --verbose
    - name: Build release
      run: cargo build --release --verbose
    # Windows is not support yet
    - name: Generate language file
      if: matrix.os != 'windows-latest'
      run: |
        ./update_translations.sh
        ./generate_translations.sh --all
    # Windows only
    - name: Add dll files
      if: matrix.os == 'windows-latest'
      run: |
        windeployqt target/debug/cemcl.exe
        windeployqt target/release/cemcl.exe
    - name: Upload artifact
      uses: actions/upload-artifact@v4.3.6
      with:
        name: artifact-${{ matrix.os }}
        path: |
          target/*/iconengines
          target/*/imageformats
          target/*/platforms
          target/*/styles
          target/*/translations
          target/*/cemcl
          target/*/cemcl.exe
          target/*/*.dll
          target/*/locale
